# https://www.stackage.org/ ghc 8.4.4 => lts 12.26
# https://www.stackage.org/lts-12.26/
resolver: lts-12.26
flags: {}
allow-newer: true
packages:
  - .
extra-deps:
  - bytestring-0.10.8.2
  - io-streams-1.5.0.1
  - optparse-applicative-0.14.3.0
  - transformers-compat-0.6.2
arch: x86_64
system-ghc: true

