---

resolver: lts-18.28
arch: x86_64
flags: {}
packages: ['.']
extra-deps:
  - bytestring-0.10.12.0
  - criterion-1.5.13.0
  - hspec-2.7.10
  - io-streams-1.5.2.1
  - optparse-applicative-0.16.1.0
  - QuickCheck-2.14.2
