# http://docs.haskellstack.org/en/stable/yaml_configuration/

allow-newer: false

# Resolver compiler version
resolver: lts-11.17

# User packages to be built
packages:
  - '.'

# Dependency packages to be pulled from upstream that are not in the resolver
extra-deps:
  - optparse-applicative-0.14.2.0
  - transformers-compat-0.5.1.4

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
system-ghc: true

# Override the architecture used by stack
arch: x86_64
